image = "proton-bridge"
version = "3.25.0"
platforms = ["linux/amd64", "linux/arm64"]
build_args = { ENV_PROTONMAIL_BRIDGE_VERSION = "v3.25.0", ENV_PROTONMAIL_BRIDGE_COMMIT = "f1f599e97167265cb0d10ad3d169269c324d9cc7" }
